<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AstroCraft.Core\AstroCraft.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.GLFW" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Input" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Maths" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Vulkan" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.KHR" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.23.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Shaders\*.spv" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Shaders\shader.vert" />
    <None Include="Shaders\shader.frag" />
  </ItemGroup>

  <Target Name="CompileShaders" BeforeTargets="Build" Condition="'$(VULKAN_SDK)' != '' and Exists('$(VULKAN_SDK)\Bin\glslc.exe')">
    <Exec Command="&quot;$(VULKAN_SDK)\Bin\glslc.exe&quot; &quot;$(ProjectDir)Shaders\shader.vert&quot; -o &quot;$(ProjectDir)Shaders\shader.vert.spv&quot;" />
    <Exec Command="&quot;$(VULKAN_SDK)\Bin\glslc.exe&quot; &quot;$(ProjectDir)Shaders\shader.frag&quot; -o &quot;$(ProjectDir)Shaders\shader.frag.spv&quot;" />
  </Target>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
