namespace AstroCraft.Core.Blocks;

public enum BlockId : ushort
{
    Air = 0,
    Stone = 1,
    Dirt = 2,
    Grass = 3,
    Sand = 4,
    Water = 5,
    Oil = 6,
    Wood = 7,
    Leaves = 8,
    Glass = 9,
    IronOre = 10,
    CopperOre = 11,
    CoalOre = 12,
    Gravel = 13,
    Bedrock = 14,
    Ice = 15,
    Snow = 16,
    Concrete = 17,
    Steel = 18,
    Bricks = 19,
    Glowstone = 20,
    Obsidian = 21,
    Clay = 22,
    Moss = 23,
    Sandstone = 24,
    Basalt = 25,
    Lava = 26,
    BirchLog = 27,
    SpruceLog = 28,
    JungleLog = 29,
    BirchLeaves = 30,
    SpruceLeaves = 31,
    JungleLeaves = 32,
    Cactus = 33,
    SnowLayer = 34,
    Podzol = 35,
    Mycelium = 36,
    Deepslate = 37,
    PackedIce = 38,
    RedSand = 39,
    JungleGrass = 40,
    Shale = 41,
    Fern = 42,
    Apple = 43,
    Cobblestone = 44,
    Granite = 45,
    PolishedGranite = 46,
    Andesite = 47,
    PolishedAndesite = 48,
    Diorite = 49,
    PolishedDiorite = 50,
    TallGrass = 51,
    FlowerRed = 52,
    FlowerYellow = 53,
    FlowerBlue = 54,
    Shrub = 55,
    ShortGrass = 56,

    // Crafting blocks (high ids — coordinate with other agents)
    Planks = 200,
    CraftingTable = 201,
    Furnace = 202,
    Torch = 203,
}
