namespace AstroCraft.Core.Blocks;

public static class BlockDisplayNames
{
    public static string GetDisplayName(BlockId id) => id switch
    {
        BlockId.Air => "Air",
        BlockId.Stone => "Stone",
        BlockId.Dirt => "Dirt",
        BlockId.Grass => "Grass",
        BlockId.Sand => "Sand",
        BlockId.Water => "Water",
        BlockId.Oil => "Oil",
        BlockId.Wood => "Wood",
        BlockId.Leaves => "Leaves",
        BlockId.Glass => "Glass",
        BlockId.IronOre => "Iron Ore",
        BlockId.CopperOre => "Copper Ore",
        BlockId.CoalOre => "Coal Ore",
        BlockId.Gravel => "Gravel",
        BlockId.Bedrock => "Bedrock",
        BlockId.Ice => "Ice",
        BlockId.Snow => "Snow",
        BlockId.Concrete => "Concrete",
        BlockId.Steel => "Steel",
        BlockId.Bricks => "Bricks",
        BlockId.Glowstone => "Glowstone",
        BlockId.Obsidian => "Obsidian",
        BlockId.Clay => "Clay",
        BlockId.Moss => "Moss",
        BlockId.Sandstone => "Sandstone",
        BlockId.Basalt => "Basalt",
        BlockId.Lava => "Lava",
        BlockId.BirchLog => "Birch Log",
        BlockId.SpruceLog => "Spruce Log",
        BlockId.JungleLog => "Jungle Log",
        BlockId.BirchLeaves => "Birch Leaves",
        BlockId.SpruceLeaves => "Spruce Leaves",
        BlockId.JungleLeaves => "Jungle Leaves",
        BlockId.Cactus => "Cactus",
        BlockId.SnowLayer => "Snow Layer",
        BlockId.Podzol => "Podzol",
        BlockId.Mycelium => "Mycelium",
        BlockId.Deepslate => "Deepslate",
        BlockId.PackedIce => "Packed Ice",
        BlockId.RedSand => "Red Sand",
        BlockId.JungleGrass => "Jungle Grass",
        BlockId.Shale => "Shale",
        BlockId.Fern => "Fern",
        BlockId.Apple => "Apple",
        BlockId.Cobblestone => "Cobblestone",
        BlockId.Granite => "Granite",
        BlockId.PolishedGranite => "Polished Granite",
        BlockId.Andesite => "Andesite",
        BlockId.PolishedAndesite => "Polished Andesite",
        BlockId.Diorite => "Diorite",
        BlockId.PolishedDiorite => "Polished Diorite",
        BlockId.TallGrass => "Tall Grass",
        BlockId.FlowerRed => "Red Flower",
        BlockId.FlowerYellow => "Yellow Flower",
        BlockId.FlowerBlue => "Blue Flower",
        BlockId.Shrub => "Shrub",
        BlockId.ShortGrass => "Grass",
        BlockId.Planks => "Planks",
        BlockId.CraftingTable => "Crafting Table",
        BlockId.Furnace => "Furnace",
        BlockId.Torch => "Torch",
        _ => id.ToString(),
    };
}
